config/routes.rb
# Rails.application.routes.draw do
  
#   resources :product_categories
#   resources :products
#   resources :cart_items, only: [:index, :create, :destroy]
#   resources :orders, only: [:create] do
#     post 'place_order', on: :collection
#   end

#   # resources :users, only: [:index]
#   root 'home#homepage'
#   get  'homepage', to: 'home#homepage'
#   get  'dashbord', to: 'home#dashbord'
#   get  'users', to: 'users#index'
  
#   devise_for :users
          
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Defines the root path route ("/")
#   # root "articles#index"
# end

Rails.application.routes.draw do
  resources :product_categories
  resources :products
  resources :cart_items, only: [:index, :create, :destroy]
  resources :orders, only: [:index, :create, :show] do
    post 'place_order', on: :collection
  end
  
  # get 'admin/orders', to: 'admin#orders', as: 'admin_orders'
  # get 'admin/download_orders', to: 'admin#download_orders', as: 'download_orders_admin'


  post '/identity_verification', to: 'home#identity_verification'

  root 'home#homepage'
  get 'homepage', to: 'home#homepage'
  get 'dashboard', to: 'home#dashboard'
  get 'users', to: 'users#index'

  post 'webhook', to: 'home#shopify_webhook'

  devise_for :users
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :set_product_category, only: %i[ show edit update destroy ]

  # GET /product_categories or /product_categories.json
  def index
    @product_categories = ProductCategory.all
  end

# GET /product_categories/1 or /product_categories/1.json
# app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    product = Product.find(params[:id])
    category_name = product.product_category.name
    render json: { product: product, category_name: category_name }
    
  end
end

  # GET /product_categories/new
  def new
    @product_category = ProductCategory.new
  end

  # GET /product_categories/1/edit
  def edit
  end

  # POST /product_categories or /product_categories.json
  def create
    @product_category = ProductCategory.new(product_category_params)

    respond_to do |format|
      if @product_category.save
        format.html { redirect_to product_category_url(@product_category), notice: "Product category was successfully created." }
        format.json { render :show, status: :created, location: @product_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_categories/1 or /product_categories/1.json
  def update
    respond_to do |format|
      if @product_category.update(product_category_params)
        format.html { redirect_to product_category_url(@product_category), notice: "Product category was successfully updated." }
        format.json { render :show, status: :ok, location: @product_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_categories/1 or /product_categories/1.json
  def destroy
    @product_category.destroy

    respond_to do |format|
      format.html { redirect_to product_categories_url, notice: "Product category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product_category
    @product_category = ProductCategory.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_category_params
    params.require(:product_category).permit(:name)
  end
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/views/product_categories/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stylish Table</title>
  <link rel="stylesheet" type="text/css" href="path/to/pcform_styles.css">
</head>
 <body>
<div class="form-container">
<%= form_with(model: product_category) do |form| %>
  <% if product_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_category.errors.count, "error") %> prohibited this product_category from being saved:</h2>

      <ul>
        <% product_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>

  
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>
</body>
</html>

app/views/product_categories/_product_category.html.erb
<table class="table" style="margin-top: 30px;">
  <thead>
    <tr>
      <th scope="row">1</th>
      <th scope="col">Product_Category</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <tr>
      <th scope="row">#</th>
      <td><strong>Name:</strong> <%= product_category.name %></td>
    </tr>
  </tbody>
</table>

app/views/product_categories/edit.html.erb
<h1>Editing product category</h1>

<%= render "form", product_category: @product_category %>

<br>

<div>
  <%= link_to "Show this product category", @product_category %> |
  <%= link_to "Back to product categories", product_categories_path %>
</div>

app/views/product_categories/index.html.erb
<div class="container mt-4">
  <p style="color: green"><%= notice %></p>
  <h1 class="text-center mb-4">Product-Categories</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @product_categories.each do |product_category| %>
        <tr>
          <td><%= product_category.name %></td>
          <td>
            <div class="row justify-content-end">
              <div class="col-auto">
                <%= link_to "Show", product_category, class: "btn btn-primary mr-2" %>
              </div>
              <div class="col-auto">
                <%= link_to "Edit", edit_product_category_path(product_category), class: "btn btn-secondary mr-2" %>
              </div>
              <div class="col-auto">
                <%= link_to "Delete", product_category, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center mt-4">
    <%= link_to "New product category", new_product_category_path, class: "btn btn-success" %>
  </div>
</div>
<%= link_to('click here go to products',{:controller => 'products'}) %>

app/views/product_categories/new.html.erb
<h1>New product category</h1>

<%= render "form", product_category: @product_category %>

<br>

<div>
  <%= link_to "Back to product categories", product_categories_path %>
</div>

app/views/product_categories/show.html.erb
<div class="container mt-4">
  <p style="color: green"><%= notice %></p>
  
  <%= render @product_category %>

  <div class="mt-4 d-flex justify-content-between">
    <%= link_to "Back to product categories", product_categories_path ,  class: "btn btn-primary mr-2"  %>
   <%# <%= link_to "Edit this product category", edit_product_category_path(@product_category),  class: "btn btn-secondary mr-2"  %> 
    <%= button_to "Destroy this product category", @product_category, method: :delete, class: "btn btn-danger" %>
  </div>
</div>