config/routes.rb
# Rails.application.routes.draw do
  
#   resources :product_categories
#   resources :products
#   resources :cart_items, only: [:index, :create, :destroy]
#   resources :orders, only: [:create] do
#     post 'place_order', on: :collection
#   end

#   # resources :users, only: [:index]
#   root 'home#homepage'
#   get  'homepage', to: 'home#homepage'
#   get  'dashbord', to: 'home#dashbord'
#   get  'users', to: 'users#index'
  
#   devise_for :users
          
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Defines the root path route ("/")
#   # root "articles#index"
# end

Rails.application.routes.draw do
  resources :product_categories
  resources :products
  resources :cart_items, only: [:index, :create, :destroy]
  resources :orders, only: [:index, :create, :show] do
    post 'place_order', on: :collection
  end
  
  # get 'admin/orders', to: 'admin#orders', as: 'admin_orders'
  # get 'admin/download_orders', to: 'admin#download_orders', as: 'download_orders_admin'


  post '/identity_verification', to: 'home#identity_verification'

  root 'home#homepage'
  get 'homepage', to: 'home#homepage'
  get 'dashboard', to: 'home#dashboard'
  get 'users', to: 'users#index'

  post 'webhook', to: 'home#shopify_webhook'

  devise_for :users
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :order, optional: true
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  
  def create
    @product = Product.find(params[:product_id])
    @order = current_order
    @cart_item = @order.cart_items.build(product: @product, user: current_user)
    
    if @cart_item.save 
      redirect_to cart_items_path, notice: 'Item added to cart'
    else
      render json: { status: 'error', message: 'Failed to add item to cart' }
    end
  end 

  def index
    @order = current_order
    @cart_items = @order.cart_items
    @total_amount = @cart_items.sum { |cart_item| cart_item.product.price }
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path, notice: "Item removed from cart"
  end

  private 

  def current_order
    @current_order ||= current_user.orders.first_or_create
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/create.html.erb
<h1>CartItems#create</h1>
<p>Find me in app/views/cart_items/create.html.erb</p>

app/views/cart_items/destroy.html.erb
<h1>CartItems#destroy</h1>
<p>Find me in app/views/cart_items/destroy.html.erb</p>

app/views/cart_items/index.html.erb
<div class="container">
  <h1 class="my-4">All Cart Items</h1>
  <% if @cart_items.present? %>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4"> <!-- Added Bootstrap grid classes -->
      <% @cart_items.each do |cart_item| %>
        <div class="col">
          <div class="card h-100 mb-4"> <!-- Added mb-4 class for vertical margin -->
            <% if cart_item.product.image.attached? %>
              <%= image_tag cart_item.product.image, class: "card-img-top", alt: cart_item.product.name %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= cart_item.product.name %></h5>
              <p class="card-text"><%= cart_item.product.description %></p>
              <h6><strong>Price:</strong> <%= number_to_currency(cart_item.product.price, unit: '₹') %></h6>
            </div>
            <div class="card-footer">
              <%= button_to "Remove", cart_item_path(cart_item), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-block" %>
            </div>
          </div>
        </div> 
      <% end %>
    </div>
    <div class="row">
      <div class="col">
        <h5>Total Amount: <%= number_to_currency(@total_amount, unit: '₹', precision: 2) %></h5>
      </div>
    </div>
    <%= form_with model: Order.new, url: place_order_orders_path, method: :post do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit "Place Order", class: "btn btn-primary" %>
    <% end %>
  <% else %>
    <p>No items in the cart.</p>
  <% end %>
  
  <%= link_to "Back to products", products_path, class: "btn btn-secondary me-2" %>
</div>