config/routes.rb
# Rails.application.routes.draw do
  
#   resources :product_categories
#   resources :products
#   resources :cart_items, only: [:index, :create, :destroy]
#   resources :orders, only: [:create] do
#     post 'place_order', on: :collection
#   end

#   # resources :users, only: [:index]
#   root 'home#homepage'
#   get  'homepage', to: 'home#homepage'
#   get  'dashbord', to: 'home#dashbord'
#   get  'users', to: 'users#index'
  
#   devise_for :users
          
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Defines the root path route ("/")
#   # root "articles#index"
# end

Rails.application.routes.draw do
  resources :product_categories
  resources :products
  resources :cart_items, only: [:index, :create, :destroy]
  resources :orders, only: [:index, :create, :show] do
    post 'place_order', on: :collection
  end
  
  # get 'admin/orders', to: 'admin#orders', as: 'admin_orders'
  # get 'admin/download_orders', to: 'admin#download_orders', as: 'download_orders_admin'


  post '/identity_verification', to: 'home#identity_verification'

  root 'home#homepage'
  get 'homepage', to: 'home#homepage'
  get 'dashboard', to: 'home#dashboard'
  get 'users', to: 'users#index'

  post 'webhook', to: 'home#shopify_webhook'

  devise_for :users
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :product_category
  validates :product_category, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  
  # GET /products or /products.json
  def index
    @products = Product.paginate(page: params[:page], per_page: 3)
    authorize! :read, Product
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
    authorize! :read, @product
  end

  # GET /products/new
  def new
    @product = Product.new
    authorize! :create, @product
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    authorize! :update, @product
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    authorize! :create, @product

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product = Product.find(params[:id])
    authorize! :update, @product

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product = Product.find(params[:id])
    authorize! :destroy, @product

    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def product_params
    params.require(:product).permit(:product_category_id, :name, :description, :price,:image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="form-container">
  <%= form_with(model: product) do |form| %>
    <% if product.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
    <%= form.label :product_category_id %>
      <%= form.select :product_category_id, options_for_select([["Select_Category", nil]] + ProductCategory.all.map { |pc| [pc.name, pc.id] }) %>
    </div>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, rows: 4 %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="field">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/products/_product.html.erb
<div class="container pt-4">
  <div class="row pt-2">
    <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
      <div class="card h-100">
        <% if product.image.attached? %>
          <%= image_tag product.image, class: "card-img-top" %>
        <% end %>

        <div class="card-body">
          
         <!--<strong>Product category:</strong>
        <%= product.product_category_id %></td>
        
        <strong>Product Category Name:</strong>
        <%= product.product_category&.name || "N/A" %></td> -->
        
          <strong>Name:</strong>
          <%= product.name %></td>

          <strong>Description:</strong>
          <%= product.description %></td>

          <strong>Price:</strong>
          <%= number_to_currency(product.price, unit: '₹') %></td>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container mt-4">
  <h1 class="text-center">Edit The Product</h1>

  <%= render "form", product: @product %>

  <div class="mt-4 d-flex justify-content-center">
  <%= link_to "Show this product", @product, class: "btn btn-primary me-2", style: "background-color: #b5d2e0; color: #000000;" %>
  <%= link_to "Back to products", products_path, class: "btn btn-secondary" , style: "background-color: #b5d2e0; color: #000000;"%>
  </div>
</div>

app/views/products/index.html.erb
<div style="margin-top: 5px; margin-right: -50px;">
    <%= link_to "View Cart Items", cart_items_path, class: "btn btn-primary mb-3", style: "float:right;" %>
</div>

<div class="container mt-4">
  <h1 class="text-center mb-4">Products</h1>

  <div id="products" class="row">
    <% @products.each do |product| %>
      <div class="col-md-4 mb-4">
        <%= render product %>
        <p class="text-center mt-2">
          <%= link_to "Show this product", product, class: "btn btn-primary" %>
        </p> 
      </div>
    <% end %>
  </div>
  <div class="text-center mt-4">
       <%= will_paginate @products %>
  </div>
    
  <div class="text-center mt-4">
    <% if  user_signed_in? && current_user.role == "admin" %>
    <%= link_to "New product", new_product_path, class: "btn btn-success" %>
    <% end %>
  </div>
  
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<!-- app/views/products/show.html.erb -->

<div style="margin-top: 5px; margin-right: -50px;">
    <%= link_to "View Cart Items", cart_items_path, class: "btn btn-primary mb-3", style: "float:right;" %>
</div>

<div class="container pt-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card custom-margin"> <!-- Add custom-margin class for additional right alignment -->
        <div class="card-body">
          <!-- Notice message -->
          <% if notice.present? %>
            <p style="color: green"><%= notice %></p>
          <% end %>

          <!-- Product Image -->
          <div class="text-center">
            <% if @product.image.attached? %>
              <%= image_tag @product.image, class: "img-fluid", alt: @product.name %>
            <% end %>
          </div>

          <!-- Product Details -->
          <h1 class="card-title text-center"><%= @product.name %></h1>
          <p class="card-text text-center"><%= @product.description %></p>
          <h4 class="card-text text-center">Price: <%= number_to_currency(@product.price, unit: '₹') %></h4>

          <!-- Add to Cart button -->
          <div class="text-center mt-4">
            <%= button_to 'Add to Cart', cart_items_path(product_id: @product.id), method: :post, class: 'btn btn-primary' %>
            <%= button_to "Destroy this product", @product, method: :delete, class: "btn btn-danger" %>
          </div>

          <!-- Action Buttons -->
          <div class="text-center mt-4">
            <%#  <%= link_to "Edit this product", edit_product_path(@product), class: "btn btn-primary me-2" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row pt-4">
    <div class="col-12 text-center">
      <%= link_to "Back to products", products_path, class: "btn btn-secondary me-2" %>
    </div>
  </div>
</div>